### ISSUE TITLE
tuple index out of range after fresh install

### ISSUE THREAD

**Issue by Brian-Webster** [hdkiller/Auto-GPT-SystemInfo#1]
# Command line

![image](https://user-images.githubusercontent.com/3356598/233796746-57146f50-5077-4268-86c3-a089be5a9d69.png)

# Steps Taken

- Pulled main branch of Auto GPT through [this commit](https://github.com/Significant-Gravitas/Auto-GPT/commit/5a95ead6083ec7e153ef72e111bf4a21f0bfed73) (midday Saturday 4/22/23)
- Used the following command to download the system info plugin to the plugins folder: Invoke-WebRequest -Uri "https://github.com/hdkiller/Auto-GPT-SystemInfo/archive/refs/heads/master.zip" -OutFile "./plugins/Auto-GPT-SystemInfo.zip"
- I did not unzip the file
- I made 3 changes to the Auto GPT .env file:
- EXECUTE_LOCAL_COMMANDS=True
- RESTRICT_TO_WORKSPACE=True
- ALLOWLISTED_PLUGINS=SystemInformationPlugin
- I attempted to start an Auto GPT session. After taking my goals, but before asking for permission to proceed with the first action, Auto GPT crashed with the output shown in the screenshot above.

# System Information

- Windows 10 
- Python 3.10.5
- AutoGPT - Master Branch, through [this commit](https://github.com/Significant-Gravitas/Auto-GPT/commit/5a95ead6083ec7e153ef72e111bf4a21f0bfed73)

# Potentially helpful context from GPT 4:

Sure, I can help you with this. The error "IndexError: tuple index out of range" is occurring because you are trying to access an index in the tuple win_ver that doesn't exist. The platform.win32_ver() function returns a tuple of strings, and the length of the tuple might be less than 5.

To fix this, you can check the length of the win_ver tuple before accessing its elements. Here's an updated version of the code block:

```python
# Get Windows version (works on Windows only)
if platform.system() == "Windows":
    win_ver = platform.win32_ver()
    win_version = f"{win_ver[0]} {win_ver[1]}"
    if len(win_ver) > 4:
        win_version += f" {win_ver[4]}"
else:
    win_version = None
```

This code will make sure that the tuple has at least 5 elements before trying to access the element at index 4. If the tuple has fewer elements, it will only include the first two elements in the win_version string.

**Comment by Brian-Webster** [comment]
Looking at the python platform docs:

https://docs.python.org/3/library/platform.html

![image](https://user-images.githubusercontent.com/3356598/233808291-88c4319a-dd98-45c1-89de-d35516eea767.png)

It looks like 

```
win_version = f"{win_ver[0]} {win_ver[1]} {win_ver[4]}"
```

should be

```
win_version = f"{win_ver[0]} {win_ver[1]} {win_ver[3]}"
```

I submitted a PR: https://github.com/hdkiller/Auto-GPT-SystemInfo/pull/2

**Comment by hdkiller** [comment]
Hello!

Thank you for the fix I've merged your changes and sorry about your inconvenience. 

Unfortunately I was not able to properly test it on a Windows machine yet.

**Comment by Brian-Webster** [comment]
No prob, happy to help. Thanks for the plugin
